### ISSUE TITLE
I can't find this extension in the 3d slicer

### ISSUE THREAD

**Issue by MENG1996** [chribaue/PETTumorSegmentation#16] opened 2019-03-07 02:10 UTC
I can't find this plugin in 3dslicer 4.10.1 according to the tutorial in Wikipedia. Was it deleted？

**Comment by chribaue** [comment] 2019-03-08 21:53
This issue seems to be specific to Slicer 4.10.x on Windows and is related to Slicer's extension build-system.

Until the issue is resolved:
  * The tutorial video demonstrates usage of the tool for Slicer 4.6.2, which you can download here: http://slicer.kitware.com/midas3/folder/274
  * The extension is also available on Windows for Slicer 4.11.0 - build 2019-03-08.

**Comment by fedorov** [comment] 2019-08-02 13:38
The Editor effect is missing in 4.10.2 stable release on mac as well, as discussed in https://discourse.slicer.org/t/pettumorsegmentationeffect/7389/8 (the extension is available and can be installed).

**Comment by jcfr** [comment] 2021-12-14 22:06
@chribaue  Could you close this issue ?

Extension is now available for both preview and stable version of Slicer

### SlicerPreview

![image](https://user-images.githubusercontent.com/219043/146086771-c2f9c1de-d2c7-42c6-a326-b387329638b9.png)

Source: https://slicer.cdash.org/index.php?project=SlicerPreview&date=2021-12-14&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=PETTumorSegmentation

### SlicerStable

![image](https://user-images.githubusercontent.com/219043/146086855-d03fbfd0-a6f7-406a-a956-5633a5de145f.png)

Source: https://slicer.cdash.org/index.php?project=SlicerStable&date=2021-12-13&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=PETTumorSegmentation

**Closed as completed** 2021-12-15 15:04 UTC
